# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('golem_type', models.CharField(max_length=60)),
                ('parts', jsonfield.fields.JSONField(default={'armors': {'arml': None, 'armr': None, 'cabin': None, 'head': None, 'legl': None, 'legr': None}, 'engine': None, 'weapons': {'l': None, 'r': None}})),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=60)),
                ('level', models.IntegerField()),
                ('part_type', models.CharField(max_length=60)),
                ('golem_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golem_tournament.Part')),
                ('defense', models.IntegerField(default=1)),
            ],
            bases=('golem_tournament.part',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golem_tournament.Part')),
                ('weapon_range', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('limit', models.IntegerField(default=0)),
            ],
            bases=('golem_tournament.part',),
        ),
    ]
