# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golem_tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golem_tournament.Part')),
            ],
            bases=('golem_tournament.part',),
        ),
    ]
